# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_175793143758247/secretstorage-feedstock/recipe, last modified Mon Sep 15 10:17:33 2025
# ------------------------------------------------

package:
  name: secretstorage
  version: 3.4.0
source:
  sha256: c46e216d6815aff8a8a18706a2fbfd8d53fcbb0dce99301881687a1b0289ef7c
  url: https://pypi.org/packages/source/s/secretstorage/secretstorage-3.4.0.tar.gz
build:
  number: '0'
  script: /home/task_175793143758247/conda-bld/secretstorage_1757931467244/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vvv
  string: py313h3e8c6aa_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.9.9 h06a4308_0
    - dbus 1.16.2 h5bd4931_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.17 h5eee18b_0
    - pip 25.2 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.7 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 78.1.1 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - cryptography >=2.0
    - dbus >=1.16.2,<2.0a0
    - jeepney >=0.6
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - secretstorage
  requires:
    - pip
about:
  description: 'This module provides a way for securely storing passwords and other
    secrets.

    It uses D-Bus Secret Service API that is supported by GNOME Keyring (since

    version 2.30) and KSecretsService.

    The main classes provided are secretstorage.Item, representing a secret item

    (that has a label, a secret and some attributes) and secretstorage.Collection,

    a place items are stored in.

    SecretStorage supports most of the functions provided by Secret Service,

    including creating and deleting items and collections, editing items, locking

    and unlocking collections (asynchronous unlocking is also supported).

    '
  dev_url: https://github.com/mitya57/secretstorage
  doc_url: https://secretstorage.readthedocs.io
  home: https://github.com/mitya57/secretstorage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Provides a way for securely storing passwords and other secrets.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CurtLH
    - ccordoba12
