# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176313455153976/certifi-feedstock/recipe, last modified Fri Nov 14 15:48:38 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.11.12
source:
  - folder: certifi
    sha256: 3e67679bfbd220da166ee43339f498b605cfa0e836383f2e7b4da2d68364c0f2
    url: https://github.com/certifi/python-certifi/archive/refs/tags/2025.11.12.tar.gz
  - folder: pip_wheel
    sha256: 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    url: https://pypi.org/packages/py3/p/pip/pip-24.3.1-py3-none-any.whl
  - folder: setuptools_wheel
    sha256: ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.6.0-py3-none-any.whl
build:
  number: '0'
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('certifi')=='2025.11.12')"
    - pytest -vv certifi/certifi/tests
  imports:
    - certifi
  requires:
    - pip
    - pytest
  source_files:
    - certifi/certifi/tests
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  home: https://certifi.io
  license: MPL-2.0
  license_family: Other
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
  skip-lints:
    - missing_python_build_tool
