# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 19 22:49:16 2024
# ------------------------------------------------

package:
  name: jansson
  version: '2.14'
source:
  sha256: c739578bf6b764aa0752db9a2fdadcfe921c78f1228c7ec0bb47fa804c55d17b
  url: https://github.com/akheron/jansson/archive/v2.14.tar.gz
build:
  number: '1'
  run_exports:
    - jansson >=2.14,<3.0a0
  string: h5eee18b_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - automake 1.16.5 pl5340h06a4308_1
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.4 h6a678d5_0
    - perl 5.34.0 h5eee18b_2
    - readline 8.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libjansson.a
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}
about:
  description: "Jansson is a C library for encoding, decoding and manipulating JSON\
    \ data.\nIts main features and design principles are:\n  Simple and intuitive\
    \ API and data model\n  Comprehensive documentation\n  No dependencies on other\
    \ libraries\n  Full Unicode support (UTF-8)\n  Extensive test suite\n"
  dev_url: https://github.com/akheron/jansson
  doc_url: https://jansson.readthedocs.io
  home: https://github.com/akheron/jansson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jansson is a C library for encoding, decoding and manipulating JSON data.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b552493c-4469-4a9f-8f85-c35dae211328
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/jansson-feedstock.git
  sha: 4bd3ab77520814613c77007a2f047f0879f8964a
