# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176400924785639/pydantic-core-feedstock/recipe, last modified Mon Nov 24 18:42:11 2025
# ------------------------------------------------

package:
  name: pydantic-core
  version: 2.41.5
source:
  sha256: 08daa51ea16ad373ffd5e7606252cc32f07bc72b28284b6bc9c6df804816476e
  url: https://pypi.org/packages/source/p/pydantic-core/pydantic_core-2.41.5.tar.gz
build:
  number: '1'
  script:
    - /home/task_176400924785639/conda-bld/pydantic-core_1764009747660/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  string: py313h498d7c9_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - cargo-bundle-licenses 0.5.0 h52d8a92_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_2
    - kernel-headers_linux-64 4.18.0 h3108a97_1
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc 15.2.0 h69a1729_7
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - rust 1.89.0 hd1a145a_0
    - rust_linux-64 1.89.0 hd1a145a_2
    - sysroot_linux-64 2.28 h3108a97_1
    - tzdata 2025b h04d1e81_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - maturin 1.9.4 py313h1c792f7_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.3 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc
    - libgcc-ng >=11.2.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing-extensions >=4.14.1
test:
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
    - pytest -v --ignore=tests/test_docstrings.py --ignore=tests/test_hypothesis.py
      --ignore=tests/validators/test_allow_partial.py --ignore=tests/validators/test_frozenset.py
      --ignore=tests/validators/test_list.py --ignore=tests/validators/test_set.py
  imports:
    - pydantic_core
  requires:
    - dirty-equals
    - hypothesis
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-timeout
    - typing-inspection
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'This package provides the core functionality for pydantic validation
    and serialization.

    '
  dev_url: https://github.com/pydantic/pydantic-core
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic-core
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Core validation logic for pydantic written in rust
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adriangb
    - dmontagu
    - pavelzw
    - samuelcolvin
    - xhochy
