# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176174487847081/annotated-types-feedstock/recipe, last modified Wed Oct 29 13:34:54 2025
# ------------------------------------------------

package:
  name: annotated-types
  version: 0.6.0
source:
  sha256: 563339e807e53ffd9c267e99fc6d9ea23eb8443c08f112651963e24e22f84a5d
  url: https://pypi.org/packages/source/a/annotated_types/annotated_types-0.6.0.tar.gz
build:
  number: '1'
  script: /home/task_176174487847081/conda-bld/annotated-types_1761744928471/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.9.9 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - hatchling 1.27.0 py313h06a4308_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pathspec 0.12.1 py313h06a4308_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - annotated_types
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'This package provides metadata objects which can be used to represent
    common constraints such as upper and lower

    bounds on scalar values and collection sizes, a Predicate marker for runtime checks,
    and descriptions of how we

    intend these metadata to be interpreted. In some cases, we also note alternative
    representations which do not

    require this package.

    '
  dev_url: https://github.com/annotated-types/annotated-types
  doc_url: https://github.com/annotated-types/annotated-types
  home: https://github.com/annotated-types/annotated-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reusable constraint types to use with typing.Annotated
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Zac-HD
    - mattwthompson
    - samuelcolvin
