# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: anaconda-auth
  version: 0.12.3
source:
  sha256: 173007c0a5686b335e9d62f10d8a19e27b185a0d4c1dda76fbc92bf355fb69f2
  url: https://github.com/anaconda/anaconda-auth/archive/refs/tags/v0.12.3.tar.gz
build:
  entry_points:
    - conda-token = anaconda_auth._conda.conda_token:cli
  number: 0
  script:
    - python -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
      -vv
    - python ./src/anaconda_auth/_conda/config.py --install
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - hatch-vcs 0.5.0 py313h06a4308_0
    - hatchling 1.27.0 py313h06a4308_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.3 h7354ed3_4
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pathspec 0.12.1 py313h06a4308_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.11 hcf712cf_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - setuptools-scm 9.2.2 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - anaconda-cli-base >=0.7.0
    - cryptography >=3.4.0
    - keyring
    - pkce
    - pydantic
    - pyjwt
    - python >=3.13,<3.14.0a0
    - python-dotenv
    - python_abi 3.13.* *_cp313
    - requests
    - semver <4
  run_constrained:
    - anaconda-cloud-auth >=0.12.3
    - conda >=23.9.0
    - conda-token >=0.7.0
test:
  commands:
    - pip check
    - python -c "from anaconda_auth import __version__; assert __version__ == '0.12.3'"
    - python -m anaconda_auth._conda.config --verify
  imports:
    - anaconda_auth
  requires:
    - conda
    - pip
  source_files:
    - pyproject.toml
about:
  description: 'A client library for Anaconda.cloud APIs to authenticate and securely
    store API keys.

    This package also provides a requests client class that handles loading the API
    key

    for requests made to Anaconda Cloud services.

    '
  dev_url: https://github.com/anaconda/anaconda-auth
  doc_url: https://anaconda.github.io/anaconda-auth/
  home: https://anaconda.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client auth library for Anaconda.cloud APIs
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - albertdefusco
    - mattkram
