# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Jul 29 05:37:20 2021
# ------------------------------------------------

package:
  name: jeepney
  version: 0.7.1
source:
  fn: jeepney-0.7.1.tar.gz
  sha256: fa9e232dfa0c498bd0b8a3a73b8d8a31978304dcef0515adc859d4e096f96f4f
  url: https://pypi.io/packages/source/j/jeepney/jeepney-0.7.1.tar.gz
build:
  noarch: python
  number: '0'
  script: FLIT_ROOT_INSTALL=1 flit install --deps none
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - brotlipy 0.7.0 py39h27cfd23_1003
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - cffi 1.14.6 py39h400218f_0
    - chardet 4.0.0 py39h06a4308_1003
    - cryptography 3.4.7 py39hd23ed53_0
    - docutils 0.17.1 py39h06a4308_1
    - flit 3.2.0 pyhd3eb1b0_0
    - flit-core 3.2.0 pyhd3eb1b0_0
    - idna 2.10 pyhd3eb1b0_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.3 py39h06a4308_0
    - pycparser 2.20 py_2
    - pyopenssl 20.0.1 pyhd3eb1b0_1
    - pysocks 1.7.1 py39h06a4308_0
    - python 3.9.5 h12debd9_4
    - readline 8.1 h27cfd23_0
    - requests 2.25.1 pyhd3eb1b0_0
    - requests_download 0.1.2 pyhd3eb1b0_1
    - setuptools 52.0.0 py39h06a4308_0
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2021a h52ac0ba_0
    - urllib3 1.26.6 pyhd3eb1b0_1
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - jeepney
  requires:
    - pip
about:
  description: 'This is a low-level, pure Python DBus protocol client. It has

    an I/O-free core, and integration modules for different event

    loops.

    '
  dev_url: https://gitlab.com/takluyver/jeepney
  doc_url: https://jeepney.readthedocs.io/en/latest/
  home: https://gitlab.com/takluyver/jeepney
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python DBus interface
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - takluyver
