# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176433224228540/click-feedstock/recipe, last modified Fri Nov 28 12:17:24 2025
# ------------------------------------------------

package:
  name: click
  version: 8.2.1
source:
  sha256: 27c491cc05d968d271d5a1db13e3b5a184636d9d930f148c50b038f0d0646202
  url: https://pypi.org/packages/source/c/click/click-8.2.1.tar.gz
build:
  number: '1'
  script: /home/task_176433224228540/conda-bld/click_1764332256338/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - flit-core 3.12.0 py313hee27c6d_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.3 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 2_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -v tests -k "not test_echo_via_pager"
  imports:
    - click
  requires:
    - pip
    - pytest
  source_files:
    - docs
    - pyproject.toml
    - tests
about:
  description: 'Click is a Python package for creating beautiful command line interfaces
    in a composable way

    with as little code as necessary. It''s the "Command Line Interface Creation Kit".

    It''s highly configurable but comes with sensible defaults out of the box.

    It aims to make the process of writing command line tools quick and fun

    while also preventing any frustration caused by the inability to implement an
    intended CLI API.

    '
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python composable command line interface toolkit
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - xylar
