# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176488869080098/anaconda-cli-base-feedstock/recipe, last modified Thu Dec  4 22:51:49 2025
# ------------------------------------------------

package:
  name: anaconda-cli-base
  version: 0.7.0
source:
  sha256: 4ebec5d913039b6ac208a4c6abed737f7ad1f311f54c14b768bd5cb266092207
  url: https://pypi.org/packages/source/a/anaconda-cli-base/anaconda_cli_base-0.7.0.tar.gz
build:
  entry_points:
    - anaconda = anaconda_cli_base.cli:app
  number: '0'
  script: /home/task_176488869080098/conda-bld/anaconda-cli-base_1764888740587/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - hatch-vcs 0.5.0 py313h06a4308_0
    - hatchling 1.27.0 py313h06a4308_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pathspec 0.12.1 py313h06a4308_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.10 hcf712cf_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - setuptools-scm 9.2.2 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - click
    - packaging >=23.0
    - pydantic-settings >=2.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - readchar
    - rich
    - tomli
    - typer >=0.17
  run_constrained:
    - anaconda-auth >=0.12.0
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0
test:
  commands:
    - pip check
    - anaconda -h
    - anaconda -V
    - python -c "from anaconda_cli_base import __version__; assert __version__ ==
      \"0.7.0\""
    - python -c "from importlib.metadata import version; assert(version('anaconda-cli-base')=='0.7.0')"
    - pytest -v tests
  imports:
    - anaconda_cli_base
  requires:
    - pip
    - pytest
    - pytest-mock
    - types-requests
  source_files:
    - tests
about:
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  dev_url: https://pypi.org/project/anaconda-cli-base
  doc_url: https://pypi.org/project/anaconda-cli-base
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - albertdefusco
    - mattkram
