# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176037557612320/rich-feedstock/recipe, last modified Mon Oct 13 17:13:10 2025
# ------------------------------------------------

package:
  name: rich
  version: 14.2.0
source:
  sha256: 589ddd6a66adbffb9d0e406da9d529a886d2c040177da4b72fad4a8563ff5afc
  url: https://github.com/Textualize/rich/archive/refs/tags/v14.2.0.tar.gz
build:
  number: '0'
  script: /home/task_176037557612320/conda-bld/rich_1760375632000/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.9.9 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.2 pyhc872135_0
    - poetry-core 2.2.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.7 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0,<3.0.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - ipywidgets >=7.5.1,<9
test:
  commands:
    - pip check
    - pytest -vv tests -k "not (test_markdown_render or test_syntax_highlight_ranges
      or test_option_no_wrap or test_python_render or test_card_render or test_brokenpipeerror
      or test_background_color_override_includes_padding)"
  imports:
    - rich
  requires:
    - attrs
    - pip
    - pytest
  source_files:
    - tests
about:
  description: "Rich is a Python library for rich text and beautiful formatting\n\
    in the terminal.The Rich API makes it easy to add color and style to\nterminal\
    \ output. Rich can also render pretty tables, progress bars,\nmarkdown, syntax\
    \ highlighted source code, tracebacks, and more \u2014 out\nof the box.\n"
  dev_url: https://github.com/Textualize/rich
  doc_url: https://rich.readthedocs.io
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the
    terminal.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
