# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Aug 18 11:25:22 2025
# ------------------------------------------------

package:
  name: jaraco.classes
  version: 3.4.0
source:
  sha256: 47a024b51d0239c0dd8c8540c6c7f484be3b8fcf0b2d85c13825780d3b3f3acd
  url: https://pypi.org/packages/source/j/jaraco.classes/jaraco.classes-3.4.0.tar.gz
build:
  number: '0'
  script: /croot/jaraco.classes_1755516327832/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.7.15 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.17 h5eee18b_0
    - packaging 25.0 py313h06a4308_0
    - pip 25.1 pyhc872135_2
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.5 h4612cfd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 78.1.1 py313h06a4308_0
    - setuptools-scm 8.3.1 py313h06a4308_1
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - more-itertools
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "import jaraco.classes.properties as p; assert hasattr(p, 'NonDataProperty')"
    - pytest -v --color=yes test_jaraco_classes.py
  files:
    - test_jaraco_classes.py
  imports:
    - jaraco
    - jaraco.classes
    - jaraco.classes.ancestry
    - jaraco.classes.meta
    - jaraco.classes.properties
  requires:
    - pip
    - pytest
about:
  description: 'jaraco.classes provides additional routines for obtaining the class
    names of an object and its parent classes,

    some useful metaclasses and methods for class properties

    '
  dev_url: https://github.com/jaraco/jaraco.classes
  doc_url: https://jaracoclasses.readthedocs.io
  home: https://github.com/jaraco/jaraco.classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utility functions for Python class constructs
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 72ff3cd4-c99d-4685-bcc5-1565ce572401
  recipe-maintainers:
    - carlodri
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jaraco.classes-feedstock.git
  sha: f8b1ad2f58f061c708bb337cf2b9633e50727e4d
