# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176363713576885/keyring-feedstock/recipe, last modified Thu Nov 20 11:12:52 2025
# ------------------------------------------------

package:
  name: keyring
  version: 25.7.0
source:
  sha256: fe01bd85eb3f8fb3dd0405defdeac9a5b4f6f0439edbb3149577f244a2e8245b
  url: https://pypi.org/packages/source/k/keyring/keyring-25.7.0.tar.gz
build:
  entry_points:
    - keyring = keyring.cli:main
  number: '0'
  script: /home/task_176363713576885/conda-bld/keyring_1763637184857/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pip 25.3 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - setuptools-scm 8.3.1 py313h06a4308_1
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - jaraco.classes
    - jaraco.context
    - jaraco.functools
    - jeepney >=0.4.2
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - secretstorage >=3.2
  run_constrained:
    - pytest-checkdocs >=2.4
    - pytest-enabler >=3.4
    - pytest-mypy >=1.0.1
    - shtab >=1.1.0
test:
  commands:
    - pip check
    - py.test -v tests
    - keyring --help
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  requires:
    - pip
    - pytest >=6,!=8.1.*
  source_files:
    - tests/*
about:
  description: 'The python keyring lib provides a easy way to access the system keyring

    service from python.  it can be used in any application that needs safe

    password storage.

    '
  dev_url: https://github.com/jaraco/keyring
  doc_url: https://pypi.org/project/keyring
  home: https://github.com/jaraco/keyring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - licode
    - tacaswell
