# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Apr 30 13:20:49 2024
# ------------------------------------------------

package:
  name: libiconv
  version: '1.16'
source:
  - patches:
      - glibc.patch
    sha256: e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
    url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
build:
  number: '3'
  run_exports:
    - libiconv >=1.16,<2.0a0
  string: h5eee18b_3
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - iconv --help
about:
  description: 'This library provides an iconv() implementation, for use on systems
    which don''t have one,

    or whose implementation cannot convert from/to Unicode.

    '
  dev_url: https://git.savannah.gnu.org/cgit/libiconv.git/tree/
  doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.16/iconv.1.html
  home: https://www.gnu.org/software/libiconv/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Provides iconv for systems which don't have one (or that cannot convert
    from/to Unicode.)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b282bf4c-934a-46d9-95f4-c6f83f849327
  recipe-maintainers:
    - jakirkham
    - jhamman
    - mingwandroid
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/libiconv-feedstock.git
  sha: 0838f2a565363f832c7d63c086327e86238dd02b
