# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: zlib
  version: 1.3.1
source:
  sha256: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
  url: https://zlib.net/zlib-1.3.1.tar.gz
build:
  number: 0
  run_exports:
    - libzlib >=1.3.1,<2.0a0
  string: hb25bd0a_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libzlib 1.3.1 hb25bd0a_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=11.2.0
    - libzlib 1.3.1 hb25bd0a_0
test:
  commands:
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test -f ${PREFIX}/include/zlib.h
  files:
    - test_compile_flags.bat
    - test_compile_flags.c
  requires:
    - gcc_linux-64 11.2.0.*
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib/tree/v1.3.1
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: OTHER
  license_file: LICENSE
  summary: A massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9f6b66c6-17e9-43de-85a1-e51171cc7f26
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/zlib-feedstock.git
  sha: 75e04258de05478db14c1c11ee6200f55a676d6a
