# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176235918788486/requests-feedstock/recipe, last modified Wed Nov  5 16:19:41 2025
# ------------------------------------------------

package:
  name: requests
  version: 2.32.5
source:
  sha256: dbba0bac56e100853db0ea71b82b4dfd5fe2bf6d3754a8893c3af500cec7d7cf
  url: https://pypi.org/packages/source/r/requests/requests-2.32.5.tar.gz
build:
  number: '1'
  script: /home/task_176235918788486/conda-bld/requests_1762359591632/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.2 pyhc872135_1
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - urllib3 >=1.21.1,<3
  run_constrained:
    - chardet >=3.0.2,<6
    - pysocks >=1.5.6,!=1.5.7
test:
  commands:
    - pip check
    - python -m conda
    - conda create -v --dry-run -n requests-test numpy
    - "pytest -v  \\\n  -k \"not (test_use_proxy_from_environment or TestRequests\
      \ or TestTimeout \\\n  or test_requests_are_updated_each_time or tests/test_requests.py::test_urllib3_retries\
      \ \\\n  or tests/test_requests.py::test_urllib3_pool_connection_closed or TestPreparingURLs\
      \ \\\n  or test_content_length_for_bytes_data or test_content_length_for_string_data_counts_bytes\
      \ \\\n  or test_urllib3_retries or test_urllib3_pool_connection_closed or test_zipped_paths_extracted)\"\
      \n"
  imports:
    - requests
  requires:
    - conda
    - pip
    - pysocks >=1.5.6,!=1.5.7
    - pytest >=6.2
    - pytest-mock
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io
  home: https://requests.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
