# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176408303339170/pydantic-feedstock/recipe, last modified Tue Nov 25 15:11:55 2025
# ------------------------------------------------

package:
  name: pydantic
  version: 2.12.4
source:
  sha256: 0f8cb9555000a4b5b617f66bfd2566264c4984b27589d3b845685983e8ea85ac
  url: https://pypi.org/packages/source/p/pydantic/pydantic-2.12.4.tar.gz
build:
  number: '0'
  script: /home/task_176408303339170/conda-bld/pydantic_1764083529211/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vvv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - hatch-fancy-pypi-readme 24.1.0 py313h06a4308_1
    - hatchling 1.27.0 py313h06a4308_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pathspec 0.12.1 py313h06a4308_1
    - pip 25.3 pyhc872135_0
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 2_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - annotated-types >=0.6.0
    - pydantic-core ==2.41.5
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing-inspection >=0.4.2
    - typing_extensions >=4.14.1
  run_constrained:
    - email-validator >=2.0.0
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('pydantic')=='2.12.4')"
    - pytest -ra -vv --tb=short tests  --ignore=tests/test_docs.py  --deselect=tests/test_types_typeddict.py::test_readonly_qualifier_warning
  imports:
    - pydantic
    - pydantic._internal
    - pydantic._internal._config
    - pydantic._internal._decorators
    - pydantic._internal._discriminated_union
    - pydantic._internal._generate_schema
    - pydantic._internal._generics
    - pydantic._internal._import_utils
    - pydantic._internal._internal_dataclass
    - pydantic._internal._mock_val_ser
    - pydantic._internal._model_construction
    - pydantic._internal._repr
    - pydantic._internal._typing_extra
    - pydantic._internal._utils
    - pydantic._internal._validators
    - pydantic._migration
    - pydantic.alias_generators
    - pydantic.color
    - pydantic.config
    - pydantic.dataclasses
    - pydantic.deprecated.decorator
    - pydantic.deprecated.json
    - pydantic.deprecated.parse
    - pydantic.deprecated.tools
    - pydantic.errors
    - pydantic.experimental.arguments_schema
    - pydantic.experimental.pipeline
    - pydantic.fields
    - pydantic.functional_serializers
    - pydantic.functional_validators
    - pydantic.json_schema
    - pydantic.main
    - pydantic.networks
    - pydantic.plugin
    - pydantic.plugin._loader
    - pydantic.type_adapter
    - pydantic.types
  requires:
    - dirty-equals
    - faker
    - jsonschema
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytz
  source_files:
    - tests
about:
  description: 'Data validation and settings management using python type hinting.

    See documentation doc_url for more details.

    '
  dev_url: https://github.com/pydantic/pydantic
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dgasmith
    - samuelcolvin
