# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Apr 25 19:43:56 2025
# ------------------------------------------------

package:
  name: python-dotenv
  version: 1.1.0
source:
  sha256: 2b9722774d3126917226cc39d0b63deb45bd9edacf8fa9b08aceee8e6d9a246d
  url: https://github.com/theskumar/python-dotenv/archive/refs/tags/v1.1.0.tar.gz
build:
  entry_points:
    - dotenv = dotenv.__main__:cli
  number: '0'
  script: /croot/python-dotenv_1745610241282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.2.25 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - pip 25.0 py313h06a4308_0
    - python 3.13.2 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.8.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - click >=5.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest tests -vv -k "not (test_set_key_permission_error or test_set_key_unauthorized_file)"
  imports:
    - dotenv
  requires:
    - pip
    - pytest >=3.9
    - sh >2
  source_files:
    - tests
about:
  description: 'Python-dotenv reads key-value pairs from a .env file and can set them
    as environment variables.

    It helps in the development of applications following the 12-factor principles.

    '
  dev_url: https://github.com/theskumar/python-dotenv/
  doc_url: https://github.com/theskumar/python-dotenv/tree/main/docs
  home: https://saurabh-kumar.com/python-dotenv/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Get and set values in your .env file in local and production servers like
    Heroku does.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 34581bc7-90e5-4b55-9ab3-77782bff0aa7
  recipe-maintainers:
    - proinsias
  remote_url: git@github.com:AnacondaRecipes/python-dotenv-feedstock.git
  sha: de34b41b8a4d3bbba0fd213281a2cee57acfccfd
