# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# C:\Users\task_176424547313736\conda-libmamba-solver-feedstock\recipe, last modified Thu Nov 27 12:13:07 2025
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 25.11.0
source:
  url: https://github.com/conda/conda-libmamba-solver/archive/refs/tags/25.11.0.tar.gz
  sha256: a187016471bc561405ea66266f26c0f81637f6e85b4d8663a6724717dc715f50
  folder: src/
build:
  number: '0'
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=25.11.0
  script: C:\\miniconda3\\conda-bld\\conda-libmamba-solver_1764245615235\\_h_env\\python.exe
    -m pip install src/ -vv --no-deps --no-build-isolation
  string: pyhdf14ebd_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.11.4 haa95532_0
    - expat 2.7.3 h9214b88_0
    - hatch-vcs 0.5.0 py314haa95532_0
    - hatchling 1.27.0 py314haa95532_1
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - openssl 3.0.18 h543e019_0
    - packaging 25.0 py314haa95532_1
    - pathspec 0.12.1 py314haa95532_1
    - pip 25.3 pyh0d26453_0
    - pluggy 1.5.0 py314haa95532_0
    - python 3.14.0 h3bc0a5a_101_cp314
    - python_abi 3.14 2_cp314
    - setuptools 80.9.0 py314haa95532_0
    - setuptools-scm 9.2.2 py314haa95532_0
    - sqlite 3.51.0 hda9a48d_0
    - tk 8.6.15 hf199647_0
    - trove-classifiers 2025.5.9.12 py314haa95532_0
    - tzdata 2025b h04d1e81_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - xz 5.6.4 h4754444_1
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  run:
    - boltons >=23.0.0
    - conda >=25.9
    - libmambapy >=2
    - msgpack-python >=1.1.1
    - python >=3.10
    - requests >=2.28.0,<3.0.0
    - zstandard >=0.15
test:
  imports:
    - conda_libmamba_solver
  commands:
    - python -c "from importlib.metadata import version; assert(version('conda-libmamba-solver')=='25.11.0')"
    - conda create --solver libmamba -n test --dry-run scipy
about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
  description: 'The conda-libmamba-solver is a new solver for the conda package manager

    which uses the solver from the mamba project behind the scenes,

    while carefully implementing conda''s functionality and expected behaviors on
    top.

    The library used by mamba to do the heavy-lifting is called libsolv.

    '
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  skip-lints:
    - avoid_noarch
    - missing_pip_check
  final: true
  copy_test_source_files: true
