# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176061348700415/typing-inspection-feedstock/recipe, last modified Thu Oct 16 11:29:16 2025
# ------------------------------------------------

package:
  name: typing-inspection
  version: 0.4.2
source:
  sha256: ba561c48a67c5958007083d386c3295464928b01faa735ab8547c5692e87f464
  url: https://pypi.org/packages/source/t/typing-inspection/typing_inspection-0.4.2.tar.gz
build:
  number: '0'
  script: /home/task_176061348700415/conda-bld/typing-inspection_1760614166875/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.9.9 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - hatchling 1.27.0 py313h06a4308_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_0
    - pathspec 0.12.1 py313h06a4308_0
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.7 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing_extensions >=4.12.0
test:
  commands:
    - pip check
    - pytest . -v
  imports:
    - typing_inspection
  requires:
    - pip
    - pytest
  source_files:
    - tests/*
about:
  description: 'A collection of runtime typing introspection tools, including a

    `typing_inspect` module that provides a consistent interface for

    inspecting types across different Python versions.

    '
  dev_url: https://github.com/pydantic/typing-inspection
  doc_url: https://pydantic.github.io/typing-inspection/0.4
  home: https://github.com/pydantic/typing-inspection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime typing introspection tools
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
