# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176463481679501/anaconda-anon-usage-feedstock/recipe, last modified Tue Dec  2 00:50:38 2025
# ------------------------------------------------

package:
  name: anaconda-anon-usage
  version: 0.7.5
source:
  sha256: 7bddccd60f43e56946b21e7392fbcddff493d67ed299404be7222050fa6c7b51
  url: https://github.com/anaconda/anaconda-anon-usage/archive/refs/tags/0.7.5.tar.gz
build:
  noarch: python
  number: '100'
  script_env:
    - NEED_SCRIPTS=no
  string: pyhb46e38b_100
requirements:
  host:
    - ca-certificates 2025.11.4 hca03da5_0
    - libcxx 20.1.8 hd7fd590_1
    - libffi 3.4.4 hca03da5_1
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 24.2 py38hca03da5_0
    - python 3.8.20 hb885b13_0
    - readline 8.3 h0b18652_0
    - setuptools 75.1.0 py38hca03da5_0
    - sqlite 3.51.0 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - wheel 0.44.0 py38hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.8
  run_constrained:
    - conda >=23.7
test:
  commands:
    - pip check
    - conda info
    - conda info --json
  imports:
    - anaconda_anon_usage
  requires:
    - conda >=23.7
    - pip
    - python 3.8.*
about:
  description: 'This package augments the request header data that conda delivers

    to package servers during index and package requests. Specifically,

    three randomly generated tokens are appended to the "user agent"

    that Conda already sends with each request.

    '
  dev_url: https://github.com/anaconda/anaconda-anon-usage/
  doc_url: https://github.com/anaconda/anaconda-anon-usage/
  home: https://github.com/anaconda/anaconda-anon-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: basic anonymous telemetry for conda clients
extra:
  copy_test_source_files: true
  final: true
  skip-lints:
    - avoid_noarch
