# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Jul 29 11:27:08 2025
# ------------------------------------------------

package:
  name: jsonpointer
  version: 3.0.0
source:
  sha256: 2b2d729f2091522d61c3b31f82e11870f60b68f43fbc705cb76bf4b832af59ef
  url: https://pypi.org/packages/source/j/jsonpointer/jsonpointer-3.0.0.tar.gz
build:
  number: '0'
  script: /croot/jsonpointer_1753788433671/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vvv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.2.25 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.17 h5eee18b_0
    - pip 25.1 pyhc872135_2
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.5 h4612cfd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 78.1.1 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.14 h993c535_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('jsonpointer')=='3.0.0')"
    - pytest -vv tests.py
  imports:
    - jsonpointer
  requires:
    - pip
    - pytest
    - python >=3.13,<3.14.0a0
  source_files:
    - tests.py
about:
  description: Library to resolve JSON Pointers according to RFC 6901
  dev_url: https://github.com/stefankoegl/python-json-pointer
  doc_url: https://python-json-pointer.readthedocs.io
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Identify specific nodes in a JSON document (RFC 6901)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ad8aee34-168a-4fa8-8bb6-f5c4863d566b
  recipe-maintainers:
    - anguslees
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jsonpointer-feedstock.git
  sha: 6fc82f746c483b32916955f3e32a700dd82138ba
