# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Aug 27 12:53:01 2025
# ------------------------------------------------

package:
  name: markdown-it-py
  version: 4.0.0
source:
  - sha256: cb0a2b4aa34f932c007117b194e945bd74e0ec24133ceb5bac59009cda1cb9f3
    url: https://pypi.org/packages/source/m/markdown-it-py/markdown_it_py-4.0.0.tar.gz
  - folder: gh
    sha256: c562899de418498f223f0c48b3d462319a64493bd3b2758e1a76f11ad8f0ae15
    url: https://github.com/executablebooks/markdown-it-py/archive/refs/tags/v4.0.0.tar.gz
build:
  entry_points:
    - markdown-it = markdown_it.cli.parse:main
  number: '0'
  script: /croot/markdown-it-py_1756299186942/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.7.15 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - flit-core 3.12.0 py313hee27c6d_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.17 h5eee18b_0
    - pip 25.1 pyhc872135_2
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.5 h4612cfd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 78.1.1 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - mdurl >=0.1,<0.2
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - commonmark >=0.9,<0.10
    - linkify-it-py >=1,<3
    - markdown >=3.4,<3.5
    - mdit-py-plugins >=0.5.0
    - mistletoe >=1.0,<2.0
    - mistune >=3.0,<4.0
    - panflute >=2.3,<2.4
    - sphinx-book-theme >=1,<2
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('markdown-it-py')=='4.0.0')"
    - pytest -k "not(test_commonmark_extras or test_table_tokens or test_file or test_use_existing_env
      or test_store_labels or test_inline_definitions or test_pretty or test_pretty_text_special)"
      -v gh/tests
    - markdown-it --help
  imports:
    - markdown_it
    - markdown_it.cli
    - markdown_it.main
    - markdown_it.presets
    - markdown_it.renderer
    - markdown_it.rules_inline
    - markdown_it.token
    - markdown_it.tree
    - markdown_it.utils
  requires:
    - linkify-it-py
    - pip
    - pytest
  source_files:
    - gh/tests
about:
  description: 'Python port of markdown-it. Markdown parsing, done right!

    '
  dev_url: https://github.com/executablebooks/markdown-it-py
  doc_url: https://github.com/executablebooks/markdown-it-py/blob/master/README.md
  home: https://github.com/executablebooks/markdown-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of markdown-it. Markdown parsing, done right!
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 73370f05-f56a-4afe-b12f-996d8a6962ea
  recipe-maintainers:
    - choldgraf
    - dopplershift
  remote_url: git@github.com:AnacondaRecipes/markdown-it-py-feedstock.git
  sha: 061af90f9abc8f724d3301d7614222b41c7d7b3b
