# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176538230483207/menuinst-feedstock/recipe, last modified Wed Dec 10 15:59:09 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.4.2
source:
  sha256: 66d5be6bd84b1f7629b5318c1364940f03c7a1058981c47d4268f107ac04ff56
  url: https://github.com/conda/menuinst/archive/2.4.2.tar.gz
build:
  entry_points:
    - menuinst = menuinst.cli:main
  missing_dso_whitelist: null
  number: '1'
  script:
    - rm -f "/home/task_176538230483207/conda-bld/menuinst_1765382366331/work/menuinst/data/osx_launcher_*"
    - rm -f "/home/task_176538230483207/conda-bld/menuinst_1765382366331/work/menuinst/data/appkit_launcher_*"
    - /home/task_176538230483207/conda-bld/menuinst_1765382366331/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
      -m pip install . -vv --no-build-isolation --no-deps
  string: py313h06a4308_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - expat 2.7.3 h7354ed3_4
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.3 h7354ed3_4
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.10 hcf712cf_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 hc2a1206_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - expat 2.7.3 h7354ed3_4
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.3 h7354ed3_4
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pip 25.3 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.10 hcf712cf_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - setuptools-scm 9.2.2 py313h06a4308_0
    - setuptools_scm 9.2.2 hd3eb1b0_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  imports:
    - menuinst
    - menuinst.api
  requires:
    - conda
    - pip
    - pydantic >=2
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'This package provides cross platform menu item installation for conda
    packages.


    If a conda package ships a menuinst JSON document under $PREFIX/Menu, conda will
    invoke

    menuinst to process the JSON file and install the menu items in your operating
    system.

    The menu items are removed when the package is uninstalled.

    '
  dev_url: https://github.com/conda/menuinst
  doc_url: https://conda.github.io/menuinst
  home: https://github.com/conda/menuinst
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
