# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176243137807904/pygments-feedstock/recipe, last modified Thu Nov  6 12:16:36 2025
# ------------------------------------------------

package:
  name: pygments
  version: 2.19.2
source:
  sha256: 636cb2477cec7f8952536970bc533bc43743542f70392ae026374600add5b887
  url: https://pypi.org/packages/source/p/pygments/pygments-2.19.2.tar.gz
build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  number: '0'
  script: /home/task_176243137807904/conda-bld/pygments_1762431407645/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - hatchling 1.27.0 py313h06a4308_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pathspec 0.12.1 py313h06a4308_1
    - pip 25.2 pyhc872135_1
    - pluggy 1.5.0 py313h06a4308_0
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - trove-classifiers 2025.5.9.12 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained: []
test:
  commands:
    - pip check
    - pygmentize -h
    - pytest -v tests  --ignore=tests/contrast/test_contrasts.py  --deselect=tests/test_basic_api.py::test_lexer_classes
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.plugin
    - pygments.styles
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'This is the source of Pygments. It is

    a generic syntax highlighter written in Python

    that supports over 500 languages and text formats,

    for use in code hosting, forums, wikis or other applications

    that need to prettify source code.

    '
  dev_url: https://github.com/pygments/pygments
  doc_url: https://pygments.org/docs
  home: https://pygments.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
    forums, wikis or other applications that need to prettify source code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - scopatz
