# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Aug 13 11:44:49 2025
# ------------------------------------------------

package:
  name: libunistring
  version: '1.3'
source:
  fn: libunistring-1.3.tar.xz
  sha256: f245786c831d25150f3dfb4317cda1acc5e3f79a5da4ad073ddca58886569527
  url: https://ftpmirror.gnu.org/libunistring/libunistring-1.3.tar.xz
build:
  number: '0'
  run_exports:
    - libunistring >=1,<2.0a0
  string: hb25bd0a_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.7 h6a678d5_0
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=11.2.0
test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}
about:
  description: 'This library provides functions for manipulating Unicode strings and

    for manipulating C strings according to the Unicode standard.

    '
  dev_url: https://git.savannah.gnu.org/gitweb/?p=libunistring.git
  doc_url: https://www.gnu.org/software/libunistring/manual/libunistring.html
  home: https://www.gnu.org/software/libunistring
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: C unicode string manipulation library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2cdea0a0-a12b-46bc-9f35-40218e9fd37a
  recipe-maintainers:
    - bgruening
    - chenghlee
    - stefan-balke
  remote_url: git@github.com:AnacondaRecipes/libunistring-feedstock.git
  sha: 8e6f0f0b878447f309b22c664ea53b916e3a2334
