# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Aug  6 05:24:24 2024
# ------------------------------------------------

package:
  name: gettext
  version: 0.21.0
source:
  - patches:
      - 0000-Add-ax_with_curses.m4-and-try-to-use-it.patch
      - use-acinit-for-libtextstyle.patch
    sha256: d20fcbb537e02dcf1383197ba05bd0734ef7bf5db06bdb241eb69b7d16b73192
    url: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.xz
build:
  env:
    - SKIP_GNULIB=--skip-gnulib
  number: '2'
  run_exports:
    - gettext >=0.21.0,<1.0a0
  string: hedfda30_2
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - autoconf-archive 2021.02.19 hd3eb1b0_0
    - automake 1.16.5 pl5340h06a4308_1
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - ca-certificates 2024.7.2 h06a4308_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gdbm 1.18 hd4cb3f1_4
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libidn2 2.3.4 h5eee18b_0
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - libunistring 0.9.10 h27cfd23_0
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.14 h5eee18b_0
    - patch 2.7.6 h7b6447c_1001
    - perl 5.34.0 h5eee18b_2
    - pkg-config 0.29.2 h1bed415_8
    - readline 8.2 h5eee18b_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - wget 1.21.4 h251f7ec_1
    - zlib 1.2.13 h5eee18b_1
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - icu 73.1 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libxml2 2.13.1 hfdd30dd_2
    - ncurses 6.4 h6a678d5_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - _openmp_mutex
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - libxml2 >=2.13.1,<2.14.0a0
    - ncurses >=6.4,<7.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextpo$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextsrc$SHLIB_EXT
about:
  description: 'GNU gettext is an important step for the GNU Translation Project,

    as it is an asset on which we may build many other steps.

    This package offers to programmers, translators, and even users,

    a well integrated set of tools and documentation.

    Specifically, the GNU gettext utilities are a set of tools

    that provides a framework to help other GNU packages produce multi-lingual messages.

    These tools include a set of conventions about how programs should be written

    to support message catalogs, a directory and file naming organization for the
    message catalogs themselves,

    a runtime library supporting the retrieval of translated messages, and a few stand-alone
    programs

    to massage in various ways the sets of translatable strings, or already translated
    strings.

    '
  dev_url: https://git.savannah.gnu.org/gitweb/?p=gettext.git
  doc_url: https://www.gnu.org/software/gettext/manual/gettext.html
  home: https://www.gnu.org/software/gettext/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Internationalization package
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 229203c6-412b-4bb5-920a-f7ef966e0465
  recipe-maintainers:
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/gettext-feedstock.git
  sha: 45586482550e35d7c8ebfcc1183c3600f7b8c625
