# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176434954674155/python_abi-feedstock/recipe, last modified Fri Nov 28 17:06:05 2025
# ------------------------------------------------

package:
  name: python_abi
  version: '3.13'
build:
  number: '3'
  string: 3_cp313
requirements:
  build: []
  run: []
  run_constrained:
    - python 3.13.* *_cp313
test:
  commands:
    - echo "hello"
about:
  description: Metapackage to select python implementation
  dev_url: https://github.com/conda-forge/python_abi-feedstock
  doc_url: https://github.com/conda-forge/python_abi-feedstock
  home: https://github.com/conda-forge/python_abi-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select python implementation
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chrisburr
    - isuruf
