# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: libcurl
  version: 8.16.0
source:
  sha256: 9459180ab4933b30d0778ddd71c91fe2911fab731c46e59b3f4c8385b1596c91
  url: https://curl.se/download/curl-8.16.0.tar.bz2
build:
  ignore_run_exports:
    - libkrb5
  number: 0
  run_exports:
    - libcurl >=8.16.0,<9.0a0
  string: heebcbe5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 4.18.0 h528b178_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.28 h528b178_0
    - tzdata 2025b h04d1e81_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - c-ares 1.34.5 hef5626c_0
    - ca-certificates 2025.9.9 h06a4308_0
    - gettext 0.21.0 hedfda30_2
    - icu 73.1 h6a678d5_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libiconv 1.16 h5eee18b_3
    - libidn2 2.3.8 hf80d704_0
    - libkrb5 1.21.3 h520c7b4_4
    - libnghttp2 1.57.0 h2d74bed_0
    - libssh2 1.11.1 h251f7ec_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libunistring 1.3 hb25bd0a_0
    - libxml2 2.13.8 hfdd30dd_0
    - lmdb 0.9.31 hb25bd0a_0
    - lz4-c 1.9.4 h6a678d5_1
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 hd233ad5_2
    - zstd 1.5.6 hc292b87_0
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc-ng >=11.2.0
    - libidn2 >=2,<3.0a0
    - libnghttp2 >=1.57.0
    - libnghttp2 >=1.57.0,<2.0a0
    - libssh2 >=1.11.1
    - libssh2 >=1.11.1,<2.0a0
    - openssl >=3.0.18,<4.0a0
    - zlib >=1.2.13,<2.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs
  home: https://curl.se
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
