# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176252480249548/sqlite-feedstock/recipe, last modified Fri Nov  7 14:16:25 2025
# ------------------------------------------------

package:
  name: sqlite
  version: 3.51.0
source:
  patches: null
  sha256: 42e26dfdd96aa2e6b1b1be5c88b0887f9959093f650d693cb02eb9c36d146ca5
  url: https://www.sqlite.org/2025/sqlite-autoconf-3510000.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.51.0,<4.0a0
  string: h2a70700_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 4.18.0 h528b178_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.28 h528b178_0
    - tzdata 2025b h04d1e81_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - ncurses 6.5 h7934f7d_0
    - readline 8.3 hc2a1206_0
    - zlib 1.2.13 hd233ad5_2
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc-ng >=11.2.0
    - ncurses >=6.5,<7.0a0
    - readline >=8.3,<9.0a0
    - zlib >=1.2.13,<2.0a0
test:
  commands:
    - sqlite3 --version
    - python -c "import sqlite3; print(sqlite3.sqlite_version)"
    - test -f $PREFIX/bin/sqlite3
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
    - readelf -d $PREFIX/lib/libsqlite3${SHLIB_EXT} | grep SONAME
  requires:
    - binutils
    - python
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine. It is the most used database engine

    in the world.

    '
  dev_url: https://sqlite.org/src/dir?ci=trunk
  doc_url: https://www.sqlite.org/docs.html
  home: https://www.sqlite.org
  license: blessing
  license_family: Other
  license_file: LICENSE.md
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - xylar
