# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176253595903435/ruamel.yaml-feedstock/recipe, last modified Fri Nov  7 17:19:20 2025
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.16
source:
  sha256: a6e587512f3c998b2225d68aa1f35111c29fad14aed561a26e73fab729ec5e5a
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.16.tar.gz
build:
  number: '0'
  script: /home/task_176253595903435/conda-bld/ruamel.yaml_1762535972567/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py313h4aee224_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 4.18.0 h528b178_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.28 h528b178_0
    - tzdata 2025b h04d1e81_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.11.4 h06a4308_0
    - expat 2.7.3 h3385a95_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.2 pyhc872135_1
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc-ng >=11.2.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - ruamel.yaml.clib >=0.2.7
  run_constrained:
    - ruamel.yaml.jinja2 >=0.2
test:
  commands:
    - pip check
  imports:
    - ruamel.yaml
  requires:
    - pip
about:
  description: A YAML parser/emitter that supports roundtrip preservation of comments,
    seq/map flow style, and map key order
  dev_url: https://sourceforge.net/projects/ruamel-yaml/
  doc_url: https://yaml.readthedocs.io
  home: https://sourceforge.net/projects/ruamel-yaml/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
