# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176191203629823/shellingham-feedstock/recipe, last modified Fri Oct 31 12:03:14 2025
# ------------------------------------------------

package:
  name: shellingham
  version: 1.5.4
source:
  sha256: 8dbca0739d487e5bd35ab3ca4b36e11c4078f3a234bfce294b0a0291363404de
  url: https://pypi.org/packages/source/s/shellingham/shellingham-1.5.4.tar.gz
build:
  number: '0'
  script: /home/task_176191203629823/conda-bld/shellingham_1761912204430/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.9.9 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - pip 25.2 pyhc872135_1
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.13.9 h7e8bc2b_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.50.2 hb25bd0a_1
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('shellingham')=='1.5.4')"
    - pytest -v tests
  imports:
    - shellingham
    - shellingham.posix
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: Shellingham detects what shell the current Python executable is running
    in.
  dev_url: https://github.com/sarugaku/shellingham/tree/master
  doc_url: https://github.com/sarugaku/shellingham#readme
  home: https://github.com/sarugaku/shellingham
  license: ISC
  license_family: OTHER
  license_file: LICENSE
  summary: Tool to Detect Surrounding Shell
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
