# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: libstdcxx-ng
  version: 15.2.0
source:
  - patches:
      - patches/0001-allow-commands-in-main-specfile.patch
      - patches/0002-patch-zoneinfo_dir_override-to-point-to-our-tzdata.patch
      - patches/0003-add-ldl-to-libstdc___la_LDFLAGS.patch
      - patches/0004-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
    sha256: 7294d65cc1a0558cb815af0ca8c7763d86f7a31199794ede3f630c0d1b0a5723
    url:
      - https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz
      - https://mirrors.ocf.berkeley.edu/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz
build:
  number: 7
  run_exports:
    strong:
      - libstdcxx
  string: hc03a8fd_7
requirements:
  host:
    - libstdcxx 15.2.0 h39759b7_7
  run:
    - libstdcxx 15.2.0 h39759b7_7
test:
  commands:
    - echo "empty wrapper for compatibility with previous naming"
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU C++ Runtime Library
extra:
  copy_test_source_files: true
  feedstock-name: ctng-compilers-feedstock
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
