# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: typer-slim
  version: 0.20.0
source:
  - folder: typer-slim
    sha256: 9fc6607b3c6c20f5c33ea9590cbeb17848667c51feee27d9e314a579ab07d1a3
    url: https://pypi.org/packages/source/t/typer-slim/typer_slim-0.20.0.tar.gz
  - folder: typer-cli
    sha256: af928da59aed5770f50e4c0f135f70ebf798d5bd00586d86d4c3015a5718a021
    url: https://pypi.org/packages/source/t/typer-cli/typer_cli-0.20.0.tar.gz
  - folder: typer
    sha256: 1aaf6494031793e4876fb0bacfa6a912b551cf43c1e63c800df8b1a866720c37
    url: https://pypi.org/packages/source/t/typer/typer-0.20.0.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '0'
  script: build-typer.sh
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.12.2 h06a4308_0
    - ld_impl_linux-64 2.44 h153f514_2
    - libexpat 2.7.3 h7354ed3_4
    - libffi 3.4.4 h6a678d5_1
    - libgcc 15.2.0 h69a1729_7
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - libuuid 1.41.5 h5eee18b_0
    - libxcb 1.17.0 h9b100fa_0
    - libzlib 1.3.1 hb25bd0a_0
    - ncurses 6.5 h7934f7d_0
    - openssl 3.0.18 hd6dcaed_0
    - packaging 25.0 py313h06a4308_1
    - pdm-backend 2.4.6 py313h893fd2c_0
    - pip 25.3 pyhc872135_0
    - pthread-stubs 0.3 h0ce48e5_1
    - pyproject_hooks 1.2.0 py313h06a4308_1
    - python 3.13.11 hcf712cf_100_cp313
    - python-build 1.3.0 py313h06a4308_1
    - python_abi 3.13 3_cp313
    - readline 8.3 hc2a1206_0
    - setuptools 80.9.0 py313h06a4308_0
    - sqlite 3.51.0 h2a70700_0
    - tk 8.6.15 h54e0aa7_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xorg-libx11 1.8.12 h9b100fa_1
    - xorg-libxau 1.0.12 h9b100fa_0
    - xorg-libxdmcp 1.1.5 h9b100fa_0
    - xorg-xorgproto 2024.1 h5eee18b_1
    - xz 5.6.4 h5eee18b_1
    - zlib 1.3.1 hb25bd0a_0
  run:
    - click >=8.0.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing_extensions >=3.7.4.3
  run_constraints:
    - rich >=10.11.0
    - shellingham >=1.3.0
    - typer 0.20.0.*
test:
  commands:
    - pip check
  requires:
    - pip
about:
  description: 'Typer is library for building CLI applications that users will love
    using and developers will love creating. Based on Python 3.6+ type hints.


    The key features are:


    Intuitive to write: Great editor support. Completion everywhere. Less time debugging.
    Designed to be easy to use and learn. Less time reading docs.

    Easy to use: It''s easy to use for the final users. Automatic help, and automatic
    completion for all shells.

    Short: Minimize code duplication. Multiple features from each parameter declaration.
    Fewer bugs.

    Start simple: The simplest example adds only 2 lines of code to your app: 1 import,
    1 function call.

    Grow large: Grow in complexity as much as you want, create arbitrarily complex
    trees of commands and groups of subcommands, with options and arguments.

    '
  dev_url: https://github.com/tiangolo/typer
  doc_url: https://typer.tiangolo.com
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: typer/LICENSE
  summary: A library for building CLI applications
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - dfornika
